site_name: "GMGC-mapper"
repo_url: "https://github.com/psj1997/GMGC-Finder"

nav:
        - 'GMGC-mapper': index.md
        - 'Install': install.md
        - 'Usage': usage.md
        - 'Output' : output.md